openapi: 3.0.3
info:
  title: AI Brain Server - Article API
  description: 아티클 관리 및 서버 운용 API
  version: 1.0.0
  contact:
    name: Z-Project Team

servers:
  - url: http://localhost:3000
    description: 로컬 개발 서버

paths:
  /articles:
    post:
      summary: 새 아티클 등록
      description: 아티클을 등록하고 벡터 DB에 청크로 저장합니다.
      operationId: createArticle
      tags:
        - Articles
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateArticleRequest'
            example:
              title: "LangChain.js 시작하기"
              url: "https://blog.example.com/langchain-intro"
              content: "LangChain은 LLM 애플리케이션 개발을 위한 프레임워크입니다..."
              tags: ["langchain", "ai", "tutorial"]
      responses:
        '201':
          description: 아티클 등록 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArticleResponse'
        '400':
          description: 잘못된 요청 (필수 필드 누락 등)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    get:
      summary: 아티클 목록 조회
      description: 등록된 아티클 목록을 페이지네이션하여 조회합니다.
      operationId: listArticles
      tags:
        - Articles
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
            minimum: 1
          description: 페이지 번호
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
            minimum: 1
            maximum: 100
          description: 페이지당 항목 수
      responses:
        '200':
          description: 아티클 목록
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArticleListResponse'

  /articles/{id}:
    get:
      summary: 아티클 상세 조회
      operationId: getArticle
      tags:
        - Articles
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: 아티클 상세 정보
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArticleResponse'
        '404':
          description: 아티클을 찾을 수 없음
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      summary: 아티클 삭제
      operationId: deleteArticle
      tags:
        - Articles
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: 삭제 완료
        '404':
          description: 아티클을 찾을 수 없음

  /articles/{id}/feedback:
    post:
      summary: 아티클 피드백 제출
      description: 아티클에 대한 피드백을 제출하고 검색 가중치를 조정합니다.
      operationId: submitArticleFeedback
      tags:
        - Articles
        - Feedback
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: 아티클 ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ArticleFeedbackRequest'
            example:
              type: "positive"
              comment: "매우 유용한 아티클입니다"
      responses:
        '200':
          description: 피드백 제출 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArticleFeedbackResponse'
        '404':
          description: 아티클을 찾을 수 없음
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    get:
      summary: 아티클 피드백 통계 조회
      operationId: getArticleFeedbackStats
      tags:
        - Articles
        - Feedback
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: 피드백 통계
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArticleFeedbackStatsResponse'
        '404':
          description: 아티클을 찾을 수 없음

components:
  schemas:
    CreateArticleRequest:
      type: object
      required:
        - title
        - url
        - content
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
          description: 아티클 제목
        url:
          type: string
          format: uri
          description: 원본 URL
        content:
          type: string
          minLength: 10
          description: 본문 내용
        tags:
          type: array
          items:
            type: string
            maxLength: 50
          maxItems: 10
          description: 태그 목록

    ArticleResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        url:
          type: string
          format: uri
        tags:
          type: array
          items:
            type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        chunkCount:
          type: integer
          description: 벡터 DB에 저장된 청크 수
        rating:
          type: number
          format: float
          minimum: 0.0
          maximum: 2.0
          description: 평균 평점 (피드백 기반)
        positiveCount:
          type: integer
          description: 긍정적 피드백 수
        negativeCount:
          type: integer
          description: 부정적 피드백 수

    ArticleListResponse:
      type: object
      properties:
        articles:
          type: array
          items:
            $ref: '#/components/schemas/ArticleResponse'
        pagination:
          type: object
          properties:
            page:
              type: integer
            limit:
              type: integer
            total:
              type: integer
            totalPages:
              type: integer

    ArticleFeedbackRequest:
      type: object
      required:
        - type
      properties:
        type:
          type: string
          enum:
            - positive
            - negative
          description: 피드백 유형
        comment:
          type: string
          maxLength: 500
          description: 피드백 코멘트 (선택)

    ArticleFeedbackResponse:
      type: object
      properties:
        message:
          type: string
        article:
          type: object
          properties:
            id:
              type: string
              format: uuid
            rating:
              type: number
              format: float
            positiveCount:
              type: integer
            negativeCount:
              type: integer

    ArticleFeedbackStatsResponse:
      type: object
      properties:
        articleId:
          type: string
          format: uuid
        rating:
          type: number
          format: float
        positiveCount:
          type: integer
        negativeCount:
          type: integer
        totalFeedbackCount:
          type: integer
        retrievalScoreModifier:
          type: number
          format: float
          description: 현재 검색 가중치

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        message:
          type: string

tags:
  - name: Articles
    description: 아티클 관리 API
  - name: Feedback
    description: 피드백 관리 API
